### ISSUE TITLE
Interface style

### ISSUE THREAD

**Issue by sampov2** [fmidev/fmi-avi-messageconverter#1]
Quick comment on the Metar interface. The interface public methods imho should be describe as public. Interface methods are alwasy public in Java, but somehow it feels wrong to rely on the language to specify the visibility of the method instead of explicitly declaring them public.

Another thing which struct me unusual is the fact that the interface declares setters for the values. Do you really need the setters or would it be better to use factories and builder patterns to produce objects of this type - so that the user never needs to know the exact class and never needs to call setters?

The same style might be elsewhere as well, but this is the class where I started wondering about this.

**Comment by ilkkarinne** [comment]
The public visibility is left out consistently from all the interfaces, as instructed by the IntelliJ IDEA code inspection for redundant modifiers. I guess it's a code style question. Not changing this for now.

The setter issue: The current implementation code uses the interface setters to modify the POJOs during their life cycle, that is, they are not immutable. Sure could use some other modification pattern too, but I see no real reason to change this.

**Comment by ilkkarinne** [comment]
Reopening this to address the note about setters in the interfaces and using the Builder pattern

**Comment by ilkkarinne** [comment]
The METAR and all other model implementation classes have now been refactored as immutables with the help of the FreeBuilder code generation tool. The interfaces members remain non-public according to the style guide followed at FMI, but they now only contain getters.
