### ISSUE TITLE
Provide common interface for builders of METAR and SPECI

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter#30]
This is a suggestion for a cleaner implementation of `METAR` and `SPECI` interfaces. Both of these could be implemented using FreeBuilder. And as both interfaces extend `MeteorologicalTerminalAirReport`, a common builder interface `MeteorologicalTerminalAirReport.Builder` could be specified (similar to suggested in #29) just like FreeBuilder would generate it, and have then both `METARImpl.Builder` and `SPECIImpl.Builder` implement it.

**Comment by ilkkarinne** [comment]
Fixed, see https://github.com/fmidev/fmi-avi-messageconverter/blob/master/src/main/java/fi/fmi/avi/model/metar/MeteorologicalTerminalAirReportBuilder.java
