### ISSUE TITLE
Allow modelling of arbitrary message types as GenericAviationWeatherMessage

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter#43]
Currently message types are restricted to ones listed in enum `AviationCodeListUser.MessageType`. It should be made an interface and an immutable `class StandardMessageType implements MessageType` class should be created as a replacement for the enum. For arbitrary message types an implementation storing any arbitrary string as name should be created, e.g. `CustomMessageType`.

**Comment by ilkkarinne** [comment]
Fixed in release https://github.com/fmidev/fmi-avi-messageconverter/releases/tag/fmi-avi-messageconverter-3.8.0 Instead of separate StandardMessageType and CustomMessageType classes there is now only one MessageType class with the standard message types as pre-defined static fields.
