### ISSUE TITLE
Make TAF interface and TAFImpl class IWXXM 3.0 compatible

### ISSUE THREAD

**Issue by ilkkarinne** [fmidev/fmi-avi-messageconverter#66]
Keep the current TAF interface and the TafImpl class methods for backward compatibility, but add three more methods in TAF:

- ```boolean isCancelReport()```,
- ```boolean isMissingReport()``` and
- ```Optional<PartialOfCompleteTimePeriod> getCancelledReportValidPeriod()```

Refactor the TAFImpl.Builder.setTAFStatus() method to set the AviationWeatherMessage.reportStatus, TAF.isCancelReport and TAF.isMissingReport instead of setting the TAF.status:

- If the TAFStatus to set is TAFStatus.CANCEL, set AviationWeatherMessage.status = AviationWeatherMessage.ReportStatus.NORMAL and TAF.isCancelReport = true
-  If the TAFStatus to set is TAFStatus.MISSING, setAviationWeatherMessage.status = AviationWeatherMessage.ReportStatus.NORMAL and TAF.isMissingMessage = true
- otherwise set setAviationWeatherMessage.status to NORMAL, CORRECTION or AMENDMENT based on the value to set and set TAF.isCancelReport = false and TAF.isMissingMessage = false

Override the generated TAFImpl.getStatus() to use TAF.reportStatus, TAF.isCancelReport and TAF.isMissingReport instead of TAFImpl_Builder.Value.status field.

Override the TAFImpl.getReferredReport() to use the TAF.cancelledReportValidPeriod and TAF.aerodrome instead of TAFImpl.Builder.Value.referredReport if TAF.isCancelReport == true.

Add consistency checks in the TAFImpl.Builder.build() method if TAF.isCancelReport == true:

- if TAF.cancelledReportValidPeriod is not set and TAF.referredReport is set, copy valid time period from referred report to cancelledReportValidPeriod
- make sure that the TAF.referredReport is not set, and TAF.cancelledReportValidPeriod and TAF.aerodrome are set.

**Comment by ilkkarinne** [comment]
I can take this one

**Comment by ilkkarinne** [comment]
Overriding TAFImpl methods does not work as these would be overridden by the generated FreeBuilder methods and not vice versa. The solution is to keep the TAFImpl fields in-sync in the builder methods.

**Comment by petringo** [comment]
@ilkkarinne I'm not quite sure I understand your problem. It should work. FreeBuilder doesn't override any implemented method. And you can override any method in the builder.

**Comment by ilkkarinne** [comment]
With the status field I think I could make it work, since the status field or the FreeBuilder methods for accessing or updating it are not needed. However with the referrredReport getter we would want to use the FreeBuilder generated fields and methods in cases where the report is not a cancel report. If I create the concrete method ```TAFReference getReferredReport()``` in TAFImpl, I would have to manage the referredReport field completely myself in TAFImpl

**Comment by petringo** [comment]
Ok I see. Yes, that's true for the referred report.
