### ISSUE TITLE
Comparison of PartialOrCompleteTimePeriod and PartialOrCompleteTimeInstant objects

### ISSUE THREAD

**Issue by ilkkarinne** [fmidev/fmi-avi-messageconverter#67]
PartialOrCompleteTimePeriod and PartialOrCompleteTimeInstant do not override equals() or hashCode() methods, and thus two objects of these kinds cannot be equals-compared based on their content.

**Comment by ilkkarinne** [comment]
I can take this one

**Comment by petringo** [comment]
Isn't FreeBuilder-generated `equals()` and `hashCode()` sufficient?

**Comment by ilkkarinne** [comment]
Good point @petringo, I guess we can rely on the FreeBuilder generated ones. The only problematic case would be if these abstract classes are implemented by others than FreeBuilder

**Comment by petringo** [comment]
We have the same problem with all the model classes. In case we need to be really sure. we can always use `ModelClass.immutableCopyOf(obj).equals(ModelClass.immutableCopyOf(other))`, although it may not be very efficient with other than the default implementations.
