### ISSUE TITLE
Add transmission sequence number in MeteorologicalBulletin model

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter#81]
Add an `String transmissionSequenceNumber` property in `MeteorologicalBulletin` model interface. It shall have an empty string as default value, denoting a non-existent value. This should be documented in javadoc.

The property shall meet the requirements specified in the [WMO Doc. 386 Manual on the Global Telecommunication System (2015 ed., upd 2020)](https://library.wmo.int/index.php?lvl=notice_display&id=21811), Part II, chapter 2.3.1.2. The value is not an integer value in the model, because it is also allowed to be a combination of three characters. The model should not implement any value sanity checking to allow working with invalid values too.

Add value class helper method `Optional<Integer> getTransmissionSequenceNumberAsInt()` mapping string value to integer whenever possible.

Add builder helper methods
* `Optional<Integer> getTransmissionSequenceNumberAsInt()` as in value class.
* `Builder setTransmissionSequenceNumberAsInt(int)` setting string value as three zero-padded digits throwing, an illegal argument exception if number is out of range.
* `Builder setTransmissionSequenceNumberAsInt(int value, int numberOfDigits)` setting string value as `numberOfDigits` zero-padded digits, throwing an illegal argument exception if number is out of range.

**Comment by petringo** [comment]
@patrick-alaspaa assign to you?

**Comment by patrick-alaspaa** [comment]
Yes please

**Comment by petringo** [comment]
This may be a bad idea after all, and should be considered not to be implemented. Sorry for messing up!
