### ISSUE TITLE
Replace GenericAviationMessage targetAerodrome property with a map of location indicators

### ISSUE THREAD

**Issue by petringo** [fmidev/fmi-avi-messageconverter#85]
Replace `Optional<Aerodrome> GenericAviationWeatherMessage.getTargetAerodrome()` with `Map<LocationIndicatorType, String> getLocationIndicators()` where key is something like

```
enum LocationIndicatorType {
    AERODROME,
    ISSUING_CENTRE,
    ISSUING_AIR_TRAFFIC_SERVICES_UNIT,
    ISSUING_AIR_TRAFFIC_SERVICES_REGION,
    ORIGINATING_METEOROLOGICAL_WATCH_OFFICE
}
```

and value is the designator as `String`, which suits better for current requirements than `Aerodrome`.

The change is needed for fmidev/aviation-message-archiver#9 . As a side effect, it will remove the additional properties of `Aerodrome` from the `GenericAviationWeatherMessage` model, that are not known to be used anywhere.

The [IWXXM](https://github.com/fmidev/fmi-avi-messageconverter-iwxxm) and [TAC](https://github.com/fmidev/fmi-avi-messageconverter-tac) parsing code must be adapted to the change.

**Comment by patrick-alaspaa** [comment]
I could take this one
